### PR TITLE
Override title of href in doc

### PR DESCRIPTION
**Pull request by NaokiTsuchiya**
When give like the following profile, title of id in the `semantic.Foo.html` is described `Foo id`.

```xml
<descriptor id="id" />
<descriptor id="Foo">
    <descriptor href="#id" title="Foo id" />
</descriptor>
```

### CODE REVIEW

**Comment by koriym** [comment]
Shouldn't other attributes be overridden as well, not just the title?
タイトルだけではなくて他のアトリビュートもオーバーライドされるべきではないですか？

@mamund Thoughts?

**Comment by mamund** [comment]
i am not yet following this idea. 

under what cases are overrides a possible benefit? and can you provide more examples?

**Comment by koriym** [comment]
This is also related to the issue of hierarchy that we talked about before.
これは以前も話した階層の問題とも関係しています。

```
"descriptor": [
    {"id": "id", "title": "identifier", def": "https://schema.org/identifier"},
    {"id": "Product", "descriptor":[
      {"href": "#id" title": product id"}
    ]}
]
```

For a resource with such a structure, we want to use `id` by itself, or `name` in `Product`, and a different title.
このような構造のリソースで、`id`単体の場合と`Product`の中にある`name`と別のtitleを使いたいと考えます。

* id "identifier"
* id in Product ""product id"

Look at this table.
このテーブルを見てください。

image

The `id` is retrieved from the `href`, so the `title` is not displayed here. However, We thought it would be more appropriate to display the title as `product id`, depending on the context in the product, rather than the original "identifier".

`id`は`href`から取得しているのでここに`title`は表示されていません。しかしオリジナルの"identifier"より、Productの中にあるコンテキストによって`product id" とtitle表示された方が適切ではないかと考えました。

**Comment by mamund** [comment]
OK, I understand now. 

i think this makes sense. we might want to see if there are values we DO and values we DO NOT want to allow overrides. also we should decide if the overrides happen only if the parent value is *missing* or if the child value should always overwrite parent values.

i don't have any ideas right now, but we can discuss as we explore the results of the PR.

if that sounds good, we can approve the PR and merge.

good?

**Comment by koriym** [comment]
I prefer the child values to always be added. This is because I want both plain `id` and `user id` titles in this example.
私は子の値が常にプラスされるのがいいと思います。この例で言えばプレーンな`id`と`user id`のどちらのタイトルも欲しいからです。

**Comment by koriym** [comment]
@NaokiTsuchiya Will see how's like only 'title' first with this PR.

**Pull request merged**
