### PR TITLE
Support link element of descriptor

### LINKED ISSUE #71: Support link element a child of descriptor
In the [spec](https://datatracker.ietf.org/doc/html/draft-amundsen-richardson-foster-alps-07#section-2.2.10),  link element a child element of the `alps` and the `descriptor` elements.

In my idea, can connect profile and schema like the following.

```xml
<descriptor id="Blog">
  <link rel="schema" href="../schema/blog.json" />
</descriptor>
```

```json
{
  "descriptor": [
    {"id": "Blog", "link": {"rel": "schema", "href": "../schema/blog.json"}}
  ]
}
```

### PR DESCRIPTION
**Pull request by NaokiTsuchiya**
Fix #71 

Here is an example.

image

I did dump a table like a descriptor, but can not dump to clear 😓

image (1)

```
# Item
 * type: semantic
 * tag: [tag1](tag.tag1.html)
 * descriptor
| id | type | title |
|---|---|---|
| [id](semantic.id.html) | semantic |  |
 * links
|rel|title|
|---|---|
| [rel1](https://github.com/koriym/app-state-diagram/) |  |
```

### CODE REVIEW

**Comment by koriym** [comment]
これ、やっぱりどれが`rel`でどれが`title`か分かりにくいですね？
relが２つようにも見えないですか？

**Comment by NaokiTsuchiya** [comment]
そうなんですよね。やっぱり以下のような感じが良いですかね。もう少し調整してみます

|rel|href|title|
|-|-|-|
| schema | https://github.com/koriym/app-state-diagram | JsonSchema |

**Comment by koriym** [comment]
hrefは長くなるし、relのリンクにしましょうか？

**Comment by NaokiTsuchiya** [comment]
Come back unexpected `<p>` element 😅

image

**Comment by koriym** [comment]
`descriptor` will have some links, like `safe` or `idempotent` there are all links?
So to have a distinction transfer link and rel link, I think `relation` is a proper term for this title?

image

(not links but relation)

Thoughts?

**Comment by mamund** [comment]
I am fine w/ a set of links. does not need to be displayed as a table.

```
<link href="http://api.example.org/documentation" title="API Help Files" rel="help" />
<link href="http://twitter.com/mamund" rel="author" />
<link href="http://api.example.org/home" />
```

could be rendered as:

```
<ul>
<li><a href="http://apl.example.org/documentation" rel="help">API Help Files</a></li>
<li><a href="http://twitter.com/mamund rel="author">author</a></li>
<li><a href="http://api.example.org/home">http://api.example.org/home</a></li>
<ul>
```

note various renderings based on what data is available within the ALPS document.

thoughtst?

**Comment by koriym** [comment]
The `rel` in the first line will disappear from the document?

**Comment by koriym** [comment]
preview of @mamund's suggestion
<ul>
<li>links</li>
<ul>
<li><a href="http://apl.example.org/documentation" rel="help">API Help Files</a></li>
<li><a href="http://twitter.com/mamund rel="author">author</a></li>
<li><a href="http://api.example.org/home">http://api.example.org/home</a></li>
<ul>
 </ul>

**Comment by koriym** [comment]
下記のように両方出してみるのも最初の @NaokiTsuchiya さんの例意外にも考えてみましたけど、@mamundさんの思い切った方法が良いように思えます。

I've thought about doing both as shown below, in addition to the first example by @NaokiTsuchiya, but I think @mamund's approach is better.
- links
   - <a href="http://apl.example.org/documentation" rel="help">API Help Files  `help`</a>
   - <a href="http://twitter.com/mamund">author</a>
   - <a href="http://api.example.org/home">http://api.example.org/home</a>
   
どうでしょうか？

**Comment by mamund** [comment]
another possibility is to show the rel as a roll-over in HTML (but that means stuffing the `a.title` property -- that might be confusing?

**Comment by koriym** [comment]
A style that requires some "action" (=roll over) to get more information (like open/close in the OPEN API) doesn't seem to fit the style of ASD documentation? 🤔

**Comment by koriym** [comment]
My understanding is that rel is very powerful, as defined by IANA.
Originally "help" alone would have been fine, just add a comment "API Help Files" to explain the rel.

**Comment by NaokiTsuchiya** [comment]
image

* relations
  * rel: repository <a rel="repository" href="https://github.com/koriym/app-state-diagram/">https://github.com/koriym/app-state-diagram/</a> Github repository

**Comment by koriym** [comment]
@NaokiTsuchiya So, we decided to use "links" instead of "relations"! I'm sorry. ><

**Comment by NaokiTsuchiya** [comment]
> @NaokiTsuchiya So, We decided to use "links" instead of "relations"! I'm sorry. ><

Fixed 👍

**Review by koriym — APPROVED** [review]

**Pull request merged**
